#FROM debian:trixie-slim as builder
FROM debian:sid-slim AS builder

ENV LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8 \
    LC_CTYPE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN apt update
RUN apt-get install -y --no-install-recommends \
    gcc \
    clang \
    sudo \
    python3 \
    python3-pip \
    build-essential \
    automake \
    autoconf \
    libtool \
    pkg-config \
    meson \
    cmake \
    git \
    nasm \
    pipx

RUN apt-get install -y --no-install-recommends \
    ffmpeg \
    p7zip

RUN apt-get install -y --no-install-recommends \
    python3-dev \
    llvm-dev \
    cython3 \
    libzimg-dev \
    libavcodec-dev \
    libavformat-dev \
    libxxhash-dev \
    libswscale-dev \
    libsoundtouch-dev \
    libfftw3-dev

# Create a non-root user (required for yay and makepkg)
RUN useradd -m builder && \
    echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

ENV SRCDIR="/usr/src/vapour"
ENV BUILDDIR="/tmp/vapour"
ENV PATCHDIR="/tmp/patches"
ENV PACKAGESDIR="/tmp/packages"

# pkg-config --variable pc_path pkg-config
# /usr/local/lib/x86_64-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig
#ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:/usr/local/lib64/pkgconfig:/usr/local/share/pkgconfig:${PKG_CONFIG_PATH}"

RUN sudo mkdir -p "${SRCDIR}" && \
    sudo chown builder:builder "${SRCDIR}"


# http://avisynth.nl/index.php/QTGMC#Core_Plugins_and_Scripts
ADD https://github.com/realfinder/AVS-Stuff/raw/refs/heads/master/avs%202.6%20and%20up/QTGMC.avsi "${SRCDIR}/qtgmc/QTGMC.avsi"
# Core
ADD https://github.com/pinterf/masktools/releases/download/2.2.30/masktools2_v2.2.30.7z "${PACKAGESDIR}/masktools2/masktools2_v2.2.30.7z"
ADD https://github.com/pinterf/mvtools/releases/download/2.7.46/mvtools-2.7.46-with-depans20240503.7z "${PACKAGESDIR}/mvtools/mvtools-2.7.46-with-depans20240503.7z"
ADD https://github.com/jpsdr/NNEDI3/releases/download/0.9.4.68/NNEDI3_v0_9_4_68.7z "${PACKAGESDIR}/nnedi3/NNEDI3_v0_9_4_68.7z"
ADD https://github.com/pinterf/RgTools/releases/download/1.2/RgTools-v1.2.7z "${PACKAGESDIR}/rgtools/RgTools-v1.2.7z"
ADD https://github.com/realfinder/AVS-Stuff/raw/master/avs%202.5%20and%20up/Zs_RF_Shared.avsi "${PACKAGESDIR}/Zs_RF_Shared/Zs_RF_Shared.avsi"
# Optional
ADD https://github.com/realfinder/AVS-Stuff/raw/master/avs%202.5%20and%20up/Vinverse_avsi.avsi "${PACKAGESDIR}/AVS-Stuff/Vinverse_avsi.avsi"
ADD https://github.com/pinterf/AddGrainC/releases/download/v1.8.4/AddGrainC-v1.8.4.7z "${PACKAGESDIR}/AddGrainC/AddGrainC-v1.8.4.7z"
ADD https://github.com/pinterf/dfttest/releases/download/1.9.7/dfttest-v1.9.7.7z "${PACKAGESDIR}/dfttest/dfttest-v1.9.7.7z"
ADD https://github.com/Asd-g/AviSynth-EEDI2/releases/download/1.0.0/EEDI2-1.0.0.7z "${PACKAGESDIR}/EEDI2/EEDI2-1.0.0.7z"
ADD https://github.com/pinterf/EEDI3/releases/download/v0.9.2.3/EEDI3_v0.9.2.3.7z "${PACKAGESDIR}/EEDI3/EEDI3_v0.9.2.3.7z"
ADD https://github.com/pinterf/fft3dfilter/releases/download/v2.12/FFT3dFilter-v2.12.7z "${PACKAGESDIR}/fft3dfilter/FFT3dFilter-v2.12.7z"
ADD https://github.com/pinterf/KNLMeansCL/releases/download/v1.1.1e/KNLMeansCL_1.1.1e_v20201112-pfmod.7z "${PACKAGESDIR}/KNLMeansCL/KNLMeansCL_1.1.1e_v20201112-pfmod.7z"
ADD https://github.com/chikuzen/PlanarTools/releases/download/0.3.0/PlanarTools-0.3.0.zip "${PACKAGESDIR}/PlanarTools/PlanarTools-0.3.0.zip"
ADD https://github.com/pinterf/TIVTC/releases/download/v1.0.30/TIVTC-v1.0.30.7z "${PACKAGESDIR}/TIVTC/TIVTC-v1.0.30.7z"
ADD https://github.com/pinterf/TIVTC/releases/download/v1.0.30/TDeint-v1.10.7z "${PACKAGESDIR}/TDeint/TDeint-v1.10.7z"
ADD https://github.com/Asd-g/yadifmod2/releases/download/0.2.8/yadifmod2-0.2.8.7z "${PACKAGESDIR}/yadifmod2/yadifmod2-0.2.8.7z"
ADD https://github.com/Asd-g/AviSynth-BWDIF/releases/download/1.3.0/BWDIF-1.3.0.7z "${PACKAGESDIR}/BWDIF/BWDIF-1.3.0.7z"

RUN mkdir -p "${SRCDIR}/vapour-synth" && \
    cd "${SRCDIR}/vapour-synth" && \
    find "${PACKAGESDIR}/" -iname "*.7z" -exec p7zip -f -d {} \;

USER builder
ENV HOME=/home/builder
ENV PIPX_HOME="$HOME/opt/pipx" \
    PIPX_BIN_DIR="$HOME/bin"
ENV PATH="$PATH:$HOME/bin"

WORKDIR "$HOME"

RUN export PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config)

COPY patches/ ${PATCHDIR}

# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=avisynthplus-git
RUN cd "${SRCDIR}" && \
    git clone https://github.com/AviSynth/AviSynthPlus.git && \
    cd AviSynthPlus && \
    git checkout v3.7.5 && \
    cmake -S "${SRCDIR}/AviSynthPlus" \
          -B "${BUILDDIR}/AviSynthPlus" \
          -G Ninja \
          -DCMAKE_INSTALL_PREFIX:PATH=/usr && \
    cmake --build "${BUILDDIR}/AviSynthPlus" && \
    sudo cmake --install "${BUILDDIR}/AviSynthPlus"

# https://gitlab.archlinux.org/archlinux/packaging/packages/vapoursynth/-/blob/main/PKGBUILD
RUN cd "${SRCDIR}" && \
    git clone https://github.com/vapoursynth/vapoursynth.git && \
    cd vapoursynth && \
    git checkout 76762f6a07d5169c21903972f67827fc108020ba && \
    ./autogen.sh && \
    CPPFLAGS="-I/usr/include/avisynth" ./configure --prefix=/usr --disable-static --libdir=/usr/lib --with-python-prefix=/usr --with-python-module-path=/usr/lib/python3/dist-packages && \
    sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool && \
    make && \
    sudo make install && \
    rm -f vapoursynth.la

# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vapoursynth-plugin-bestsource-git
RUN cd "${SRCDIR}" && \
    git clone https://github.com/vapoursynth/bestsource.git && \
    cd bestsource && \
    git checkout R17 && \
    git submodule init && \
    git config submodule.libp2p.url "https://github.com/sekrit-twc/libp2p.git" && \
    git -c protocol.file.allow=always submodule update && \
    rm -rf vapoursynth AviSynthPlus && \
    git apply ${PATCHDIR}/bestsource/0001-meson-fix-include_directories.patch && \
    git apply ${PATCHDIR}/bestsource/0002-fix-headers-path.patch && \
    mkdir -p "${BUILDDIR}/bestsource" && \
    cd "${BUILDDIR}/bestsource" && \
    meson setup "${SRCDIR}/bestsource" --prefix=/usr --libdir /usr/lib/vapoursynth && \
    ninja && \
    sudo ninja install

# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ffms2-git
RUN cd "${SRCDIR}" && \
    git clone https://github.com/FFMS/ffms2 && \
    cd ffms2 && \
    git checkout 5.0 && \
    rm -fr src/vapoursynth/{Vapoursynth,VSHelper}.h && \
    patch -p1 -i "${PATCHDIR}/ffms2/esee.patch" && \
    mkdir -p src/config && \
    autoreconf -ivf && \
    ./configure --enable-static=no --enable-shared=yes --enable-avisynth --prefix=/usr --libdir=/usr/lib && \
    make && \
    sudo make install && \
    sudo mkdir -p /usr/lib/vapoursynth && \
    sudo ln -sf /usr/lib/libffms2.so /usr/lib/vapoursynth/libffms2.so

# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vapoursynth-plugin-mvtools-git
RUN cd "${SRCDIR}" && \
    git clone https://github.com/dubhater/vapoursynth-mvtools.git && \
    cd vapoursynth-mvtools && \
    git checkout v26 && \
    git apply ${PATCHDIR}/vapoursynth-mvtools/use-system-vapoursynth.patch && \
    git apply ${PATCHDIR}/vapoursynth-mvtools/meson-avx2-fix-incdir.patch && \
    git apply ${PATCHDIR}/vapoursynth-mvtools/fix-headers-path.patch && \
    mkdir -p "${BUILDDIR}/vapoursynth-mvtools" && \
    cd "${BUILDDIR}/vapoursynth-mvtools" && \
    meson setup "${SRCDIR}/vapoursynth-mvtools" --prefix=/usr --libdir /usr/lib/vapoursynth && \
    ninja && \
    sudo ninja install
 
# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vapoursynth-plugin-znedi3-git
RUN cd "${SRCDIR}" && \
    git clone https://github.com/sekrit-twc/znedi3 && \
    cd znedi3 && \
    git config submodule.vsplugin/vsxx.url "https://github.com/sekrit-twc/vsxx.git" && \
    git config submodule.graphengine.url "https://github.com/sekrit-twc/graphengine.git" && \
    git -c protocol.file.allow=always submodule update --init \
        vsxx \
        graphengine && \
    rm -fr vsxx/VapourSynth && \
    make X86=0 X86_AVX512=0 && \
    sudo mkdir -p /usr/lib/vapoursynth && \
    sudo cp vsznedi3.so /usr/lib/vapoursynth/libvsznedi3.so

# https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=avisynth-plugin-masktools2-git
RUN cd "${SRCDIR}" && \
    git clone https://github.com/pinterf/masktools.git && \
    cd masktools && \
    cmake \
       -B "${BUILDDIR}/masktool" \
       -S "${SRCDIR}/masktools" \
       -G Ninja \
       -DCMAKE_BUILD_TYPE=None \
       -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build "${BUILDDIR}/masktool" && \
    sudo cmake --install "${BUILDDIR}/masktool"

